project_id = "icfizajxhgkxuwunhvtp"

[functions.wasata-ai-chat]
verify_jwt = false

[functions.wasata-speech-to-text]
verify_jwt = false

[functions.wasata-text-to-speech]
verify_jwt = false

[functions.send-rental-notification]
verify_jwt = false

[functions.generate-property-description]
verify_jwt = false

[functions.generate-smart-prices]
verify_jwt = false

[functions.send-sms]
verify_jwt = false

[functions.process-scheduled-messages]
verify_jwt = false

[functions.send-property-email]
verify_jwt = false

[functions.publish-business-card]
verify_jwt = false
