/**
 * ComprehensiveAppSettings.tsx
 * إعدادات التطبيق الشامل - مركز التحكم الموحد
 * يجمع إعدادات جميع الميزات في مكان واحد
 */

import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Switch } from '@/components/ui/switch';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { Separator } from '@/components/ui/separator';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { 
  Settings,
  Globe,
  Layout,
  Users,
  Share2,
  Sparkles,
  Calculator,
  Calendar,
  BarChart3,
  Bell,
  UserPlus,
  CreditCard,
  Newspaper,
  ChevronLeft,
  Shield,
  Eye,
  EyeOff,
  Palette,
  Volume2,
  Clock,
  MessageSquare,
  Building2,
  Home,
  X,
} from 'lucide-react';
import { useToast } from '@/hooks/use-toast';

interface SettingsSection {
  id: string;
  icon: React.ElementType;
  label: string;
  description: string;
  color: string;
}

const SETTINGS_SECTIONS: SettingsSection[] = [
  {
    id: 'public-platform',
    icon: Globe,
    label: 'منصة النشر العامه',
    description: 'إعدادات صفحة العرض العامة للعملاء',
    color: '#01411C',
  },
  {
    id: 'my-platform',
    icon: Layout,
    label: 'منصتي',
    description: 'إعدادات المنصة الشخصية وتبويباتها',
    color: '#065f41',
  },
  {
    id: 'crm',
    icon: Users,
    label: 'إدارة العملاء',
    description: 'إعدادات نظام إدارة علاقات العملاء',
    color: '#D4AF37',
  },
  {
    id: 'platform-publishing',
    icon: Share2,
    label: 'التواصل الاجتماعي',
    description: 'إعدادات النشر على منصات التواصل الاجتماعي',
    color: '#10b981',
  },
  {
    id: 'smart-opportunities',
    icon: Sparkles,
    label: 'الفرص الذكية',
    description: 'إعدادات نظام اكتشاف الفرص الذكية',
    color: '#8b5cf6',
  },
  {
    id: 'calculator',
    icon: Calculator,
    label: 'الحاسبة السريعة',
    description: 'إعدادات الحاسبة العقارية',
    color: '#f59e0b',
  },
  {
    id: 'calendar',
    icon: Calendar,
    label: 'التقويم',
    description: 'إعدادات المواعيد والتذكيرات',
    color: '#3b82f6',
  },
  {
    id: 'analytics',
    icon: BarChart3,
    label: 'التحليلات والبيانات',
    description: 'إعدادات لوحة التحليلات والتقارير',
    color: '#ec4899',
  },
  {
    id: 'notifications',
    icon: Bell,
    label: 'الإشعارات',
    description: 'إعدادات جميع أنواع الإشعارات',
    color: '#ef4444',
  },
  {
    id: 'team-management',
    icon: UserPlus,
    label: 'إدارة الفريق',
    description: 'إعدادات الفريق والصلاحيات',
    color: '#06b6d4',
  },
  {
    id: 'business-card',
    icon: CreditCard,
    label: 'بطاقة أعمالي الرسمية',
    description: 'إعدادات البطاقة الرقمية',
    color: '#D4AF37',
  },
  {
    id: 'news',
    icon: Newspaper,
    label: 'الأخبار',
    description: 'إعدادات شريط الأخبار العقارية',
    color: '#01411C',
  },
  {
    id: 'ai-assistant',
    icon: Sparkles,
    label: 'المساعد الذكي العائم',
    description: 'إعدادات وساطه AI والفقاعة العائمة',
    color: '#8b5cf6',
  },
];

interface ComprehensiveAppSettingsProps {
  isOpen: boolean;
  onClose: () => void;
}

export default function ComprehensiveAppSettings({ isOpen, onClose }: ComprehensiveAppSettingsProps) {
  const [activeSection, setActiveSection] = useState<string | null>(null);
  const { toast } = useToast();

  // إعدادات كل قسم
  const [settings, setSettings] = useState({
    // منصة النشر العامة
    publicPlatform: {
      showBrokerInfo: true,
      showContactButtons: true,
      showSocialLinks: true,
      allowDirectMessages: true,
      showPropertyViews: true,
      enableShareButtons: true,
    },
    // منصتي
    myPlatform: {
      defaultTab: 'platform',
      showPinnedFirst: true,
      gridView: true,
      showPriceRange: true,
      enableFilters: true,
      showStats: true,
    },
    // إدارة العملاء
    crm: {
      kanbanView: true,
      showRecentCalls: true,
      autoSaveNotes: true,
      showCustomerType: true,
      showInterestLevel: true,
      enableQuickActions: true,
    },
    // التواصل الاجتماعي
    platformPublishing: {
      autoSync: false,
      defaultPlatforms: ['wasalt', 'aqar'],
      includeWatermark: true,
      autoGenerateDescription: true,
      includeHashtags: true,
      notifyOnPublish: true,
    },
    // الفرص الذكية
    smartOpportunities: {
      enabled: true,
      autoRotation: true,
      notifyOnNew: true,
      showMatchScore: true,
      filterByLocation: true,
      minimumScore: 70,
    },
    // الحاسبة السريعة
    calculator: {
      defaultCurrency: 'SAR',
      showTaxCalculation: true,
      showCommission: true,
      saveHistory: true,
      quickPresets: true,
    },
    // التقويم
    calendar: {
      defaultView: 'week',
      showReminders: true,
      reminderMinutes: 30,
      syncWithGoogle: false,
      showHolidays: true,
      workingHoursOnly: false,
    },
    // التحليلات
    analytics: {
      showCharts: true,
      defaultPeriod: '30days',
      enableExport: true,
      showComparisons: true,
      realTimeUpdates: true,
    },
    // الإشعارات
    notifications: {
      soundEnabled: true,
      pushEnabled: true,
      emailEnabled: false,
      smsEnabled: false,
      quietHours: false,
      quietStart: '22:00',
      quietEnd: '08:00',
    },
    // إدارة الفريق
    teamManagement: {
      allowMemberInvites: true,
      showMemberStats: true,
      autoAssignLeads: false,
      shareCustomers: true,
      notifyOnAssignment: true,
    },
    // بطاقة الأعمال
    businessCard: {
      showQRCode: true,
      showSocialLinks: true,
      showFalLicense: true,
      enableVCard: true,
      trackViews: true,
    },
    // الأخبار
    news: {
      autoScroll: true,
      scrollSpeed: 'medium',
      showImages: true,
      categories: ['market', 'regulations', 'projects'],
      refreshInterval: 30,
    },
    // المساعد الذكي
    aiAssistant: {
      bubbleEnabled: true,
      autoSpeak: false,
      showOnAllPages: true,
      position: 'bottom-right',
      voiceEnabled: true,
      quickSuggestions: true,
    },
  });

  const updateSetting = (section: string, key: string, value: any) => {
    setSettings(prev => ({
      ...prev,
      [section]: {
        ...prev[section as keyof typeof prev],
        [key]: value,
      },
    }));
  };

  const saveSettings = () => {
    localStorage.setItem('app_comprehensive_settings', JSON.stringify(settings));
    toast({
      title: 'تم الحفظ',
      description: 'تم حفظ الإعدادات بنجاح',
    });
  };

  const renderSectionSettings = (sectionId: string) => {
    switch (sectionId) {
      case 'public-platform':
        return (
          <div className="space-y-4">
            <SettingToggle
              label="عرض معلومات الوسيط"
              description="إظهار بيانات الوسيط في الصفحة العامة"
              checked={settings.publicPlatform.showBrokerInfo}
              onChange={(v) => updateSetting('publicPlatform', 'showBrokerInfo', v)}
            />
            <SettingToggle
              label="أزرار التواصل"
              description="إظهار أزرار الاتصال والواتساب"
              checked={settings.publicPlatform.showContactButtons}
              onChange={(v) => updateSetting('publicPlatform', 'showContactButtons', v)}
            />
            <SettingToggle
              label="روابط التواصل الاجتماعي"
              description="عرض روابط حسابات التواصل الاجتماعي"
              checked={settings.publicPlatform.showSocialLinks}
              onChange={(v) => updateSetting('publicPlatform', 'showSocialLinks', v)}
            />
            <SettingToggle
              label="الرسائل المباشرة"
              description="السماح للزوار بإرسال رسائل مباشرة"
              checked={settings.publicPlatform.allowDirectMessages}
              onChange={(v) => updateSetting('publicPlatform', 'allowDirectMessages', v)}
            />
            <SettingToggle
              label="عرض عدد المشاهدات"
              description="إظهار عدد مشاهدات العقار"
              checked={settings.publicPlatform.showPropertyViews}
              onChange={(v) => updateSetting('publicPlatform', 'showPropertyViews', v)}
            />
            <SettingToggle
              label="أزرار المشاركة"
              description="تفعيل أزرار مشاركة العقار"
              checked={settings.publicPlatform.enableShareButtons}
              onChange={(v) => updateSetting('publicPlatform', 'enableShareButtons', v)}
            />
          </div>
        );

      case 'my-platform':
        return (
          <div className="space-y-4">
            <SettingToggle
              label="عرض المثبتة أولاً"
              description="عرض العقارات المثبتة في البداية"
              checked={settings.myPlatform.showPinnedFirst}
              onChange={(v) => updateSetting('myPlatform', 'showPinnedFirst', v)}
            />
            <SettingToggle
              label="عرض شبكي"
              description="استخدام العرض الشبكي بدلاً من القائمة"
              checked={settings.myPlatform.gridView}
              onChange={(v) => updateSetting('myPlatform', 'gridView', v)}
            />
            <SettingToggle
              label="نطاق الأسعار"
              description="عرض نطاق الأسعار في البطاقات"
              checked={settings.myPlatform.showPriceRange}
              onChange={(v) => updateSetting('myPlatform', 'showPriceRange', v)}
            />
            <SettingToggle
              label="الفلاتر"
              description="تفعيل فلاتر البحث المتقدمة"
              checked={settings.myPlatform.enableFilters}
              onChange={(v) => updateSetting('myPlatform', 'enableFilters', v)}
            />
            <SettingToggle
              label="الإحصائيات"
              description="عرض إحصائيات المنصة"
              checked={settings.myPlatform.showStats}
              onChange={(v) => updateSetting('myPlatform', 'showStats', v)}
            />
          </div>
        );

      case 'crm':
        return (
          <div className="space-y-4">
            <SettingToggle
              label="عرض كانبان"
              description="استخدام لوحة كانبان لإدارة العملاء"
              checked={settings.crm.kanbanView}
              onChange={(v) => updateSetting('crm', 'kanbanView', v)}
            />
            <SettingToggle
              label="المكالمات الأخيرة"
              description="عرض عمود المكالمات الأخيرة"
              checked={settings.crm.showRecentCalls}
              onChange={(v) => updateSetting('crm', 'showRecentCalls', v)}
            />
            <SettingToggle
              label="حفظ تلقائي للملاحظات"
              description="حفظ الملاحظات تلقائياً أثناء الكتابة"
              checked={settings.crm.autoSaveNotes}
              onChange={(v) => updateSetting('crm', 'autoSaveNotes', v)}
            />
            <SettingToggle
              label="نوع العميل"
              description="عرض تصنيف نوع العميل"
              checked={settings.crm.showCustomerType}
              onChange={(v) => updateSetting('crm', 'showCustomerType', v)}
            />
            <SettingToggle
              label="مستوى الاهتمام"
              description="عرض مستوى اهتمام العميل"
              checked={settings.crm.showInterestLevel}
              onChange={(v) => updateSetting('crm', 'showInterestLevel', v)}
            />
            <SettingToggle
              label="الإجراءات السريعة"
              description="تفعيل أزرار الإجراءات السريعة"
              checked={settings.crm.enableQuickActions}
              onChange={(v) => updateSetting('crm', 'enableQuickActions', v)}
            />
          </div>
        );

      case 'platform-publishing':
        return (
          <div className="space-y-4">
            <SettingToggle
              label="المزامنة التلقائية"
              description="مزامنة التحديثات تلقائياً مع المنصات"
              checked={settings.platformPublishing.autoSync}
              onChange={(v) => updateSetting('platformPublishing', 'autoSync', v)}
            />
            <SettingToggle
              label="العلامة المائية"
              description="إضافة علامة مائية للصور"
              checked={settings.platformPublishing.includeWatermark}
              onChange={(v) => updateSetting('platformPublishing', 'includeWatermark', v)}
            />
            <SettingToggle
              label="توليد الوصف تلقائياً"
              description="استخدام الذكاء الاصطناعي لكتابة الوصف"
              checked={settings.platformPublishing.autoGenerateDescription}
              onChange={(v) => updateSetting('platformPublishing', 'autoGenerateDescription', v)}
            />
            <SettingToggle
              label="الهاشتاقات"
              description="إضافة هاشتاقات تلقائياً"
              checked={settings.platformPublishing.includeHashtags}
              onChange={(v) => updateSetting('platformPublishing', 'includeHashtags', v)}
            />
            <SettingToggle
              label="إشعار عند النشر"
              description="إرسال إشعار عند نشر العقار بنجاح"
              checked={settings.platformPublishing.notifyOnPublish}
              onChange={(v) => updateSetting('platformPublishing', 'notifyOnPublish', v)}
            />
          </div>
        );

      case 'smart-opportunities':
        return (
          <div className="space-y-4">
            <SettingToggle
              label="تفعيل الفرص الذكية"
              description="تشغيل نظام اكتشاف الفرص"
              checked={settings.smartOpportunities.enabled}
              onChange={(v) => updateSetting('smartOpportunities', 'enabled', v)}
            />
            <SettingToggle
              label="التدوير التلقائي"
              description="توزيع الفرص تلقائياً على الفريق"
              checked={settings.smartOpportunities.autoRotation}
              onChange={(v) => updateSetting('smartOpportunities', 'autoRotation', v)}
            />
            <SettingToggle
              label="إشعار بالفرص الجديدة"
              description="إرسال إشعار عند ظهور فرصة جديدة"
              checked={settings.smartOpportunities.notifyOnNew}
              onChange={(v) => updateSetting('smartOpportunities', 'notifyOnNew', v)}
            />
            <SettingToggle
              label="درجة التطابق"
              description="عرض نسبة تطابق الفرصة"
              checked={settings.smartOpportunities.showMatchScore}
              onChange={(v) => updateSetting('smartOpportunities', 'showMatchScore', v)}
            />
            <SettingToggle
              label="تصفية حسب الموقع"
              description="عرض الفرص في منطقتك فقط"
              checked={settings.smartOpportunities.filterByLocation}
              onChange={(v) => updateSetting('smartOpportunities', 'filterByLocation', v)}
            />
          </div>
        );

      case 'calculator':
        return (
          <div className="space-y-4">
            <SettingToggle
              label="حساب الضريبة"
              description="تضمين ضريبة القيمة المضافة"
              checked={settings.calculator.showTaxCalculation}
              onChange={(v) => updateSetting('calculator', 'showTaxCalculation', v)}
            />
            <SettingToggle
              label="حساب العمولة"
              description="إظهار حساب عمولة الوساطة"
              checked={settings.calculator.showCommission}
              onChange={(v) => updateSetting('calculator', 'showCommission', v)}
            />
            <SettingToggle
              label="حفظ السجل"
              description="حفظ سجل الحسابات السابقة"
              checked={settings.calculator.saveHistory}
              onChange={(v) => updateSetting('calculator', 'saveHistory', v)}
            />
            <SettingToggle
              label="القوالب السريعة"
              description="إظهار قوالب الحساب الجاهزة"
              checked={settings.calculator.quickPresets}
              onChange={(v) => updateSetting('calculator', 'quickPresets', v)}
            />
          </div>
        );

      case 'calendar':
        return (
          <div className="space-y-4">
            <SettingToggle
              label="التذكيرات"
              description="تفعيل تذكيرات المواعيد"
              checked={settings.calendar.showReminders}
              onChange={(v) => updateSetting('calendar', 'showReminders', v)}
            />
            <SettingToggle
              label="العطلات الرسمية"
              description="عرض العطلات الرسمية في التقويم"
              checked={settings.calendar.showHolidays}
              onChange={(v) => updateSetting('calendar', 'showHolidays', v)}
            />
            <SettingToggle
              label="ساعات العمل فقط"
              description="عرض ساعات العمل فقط"
              checked={settings.calendar.workingHoursOnly}
              onChange={(v) => updateSetting('calendar', 'workingHoursOnly', v)}
            />
          </div>
        );

      case 'analytics':
        return (
          <div className="space-y-4">
            <SettingToggle
              label="الرسوم البيانية"
              description="عرض الرسوم البيانية التفاعلية"
              checked={settings.analytics.showCharts}
              onChange={(v) => updateSetting('analytics', 'showCharts', v)}
            />
            <SettingToggle
              label="تصدير البيانات"
              description="تفعيل تصدير التقارير"
              checked={settings.analytics.enableExport}
              onChange={(v) => updateSetting('analytics', 'enableExport', v)}
            />
            <SettingToggle
              label="المقارنات"
              description="عرض مقارنات الفترات"
              checked={settings.analytics.showComparisons}
              onChange={(v) => updateSetting('analytics', 'showComparisons', v)}
            />
            <SettingToggle
              label="التحديث الفوري"
              description="تحديث البيانات في الوقت الفعلي"
              checked={settings.analytics.realTimeUpdates}
              onChange={(v) => updateSetting('analytics', 'realTimeUpdates', v)}
            />
          </div>
        );

      case 'notifications':
        return (
          <div className="space-y-4">
            <SettingToggle
              label="صوت الإشعارات"
              description="تشغيل صوت عند وصول إشعار"
              checked={settings.notifications.soundEnabled}
              onChange={(v) => updateSetting('notifications', 'soundEnabled', v)}
            />
            <SettingToggle
              label="إشعارات الدفع"
              description="إشعارات المتصفح/الجوال"
              checked={settings.notifications.pushEnabled}
              onChange={(v) => updateSetting('notifications', 'pushEnabled', v)}
            />
            <SettingToggle
              label="إشعارات البريد"
              description="إرسال إشعارات عبر البريد الإلكتروني"
              checked={settings.notifications.emailEnabled}
              onChange={(v) => updateSetting('notifications', 'emailEnabled', v)}
            />
            <SettingToggle
              label="إشعارات SMS"
              description="إرسال رسائل نصية"
              checked={settings.notifications.smsEnabled}
              onChange={(v) => updateSetting('notifications', 'smsEnabled', v)}
            />
            <SettingToggle
              label="ساعات الهدوء"
              description="إيقاف الإشعارات في أوقات محددة"
              checked={settings.notifications.quietHours}
              onChange={(v) => updateSetting('notifications', 'quietHours', v)}
            />
          </div>
        );

      case 'team-management':
        return (
          <div className="space-y-4">
            <SettingToggle
              label="دعوة الأعضاء"
              description="السماح للأعضاء بدعوة آخرين"
              checked={settings.teamManagement.allowMemberInvites}
              onChange={(v) => updateSetting('teamManagement', 'allowMemberInvites', v)}
            />
            <SettingToggle
              label="إحصائيات الأعضاء"
              description="عرض إحصائيات أداء الأعضاء"
              checked={settings.teamManagement.showMemberStats}
              onChange={(v) => updateSetting('teamManagement', 'showMemberStats', v)}
            />
            <SettingToggle
              label="التوزيع التلقائي"
              description="توزيع العملاء الجدد تلقائياً"
              checked={settings.teamManagement.autoAssignLeads}
              onChange={(v) => updateSetting('teamManagement', 'autoAssignLeads', v)}
            />
            <SettingToggle
              label="مشاركة العملاء"
              description="السماح بمشاركة بيانات العملاء"
              checked={settings.teamManagement.shareCustomers}
              onChange={(v) => updateSetting('teamManagement', 'shareCustomers', v)}
            />
            <SettingToggle
              label="إشعار عند التعيين"
              description="إشعار العضو عند تعيين عميل له"
              checked={settings.teamManagement.notifyOnAssignment}
              onChange={(v) => updateSetting('teamManagement', 'notifyOnAssignment', v)}
            />
          </div>
        );

      case 'business-card':
        return (
          <div className="space-y-4">
            <SettingToggle
              label="رمز QR"
              description="عرض رمز QR في البطاقة"
              checked={settings.businessCard.showQRCode}
              onChange={(v) => updateSetting('businessCard', 'showQRCode', v)}
            />
            <SettingToggle
              label="روابط التواصل"
              description="عرض روابط مواقع التواصل"
              checked={settings.businessCard.showSocialLinks}
              onChange={(v) => updateSetting('businessCard', 'showSocialLinks', v)}
            />
            <SettingToggle
              label="رخصة فال"
              description="عرض رقم رخصة فال"
              checked={settings.businessCard.showFalLicense}
              onChange={(v) => updateSetting('businessCard', 'showFalLicense', v)}
            />
            <SettingToggle
              label="تحميل vCard"
              description="تفعيل زر تحميل جهة الاتصال"
              checked={settings.businessCard.enableVCard}
              onChange={(v) => updateSetting('businessCard', 'enableVCard', v)}
            />
            <SettingToggle
              label="تتبع المشاهدات"
              description="تسجيل عدد مشاهدات البطاقة"
              checked={settings.businessCard.trackViews}
              onChange={(v) => updateSetting('businessCard', 'trackViews', v)}
            />
          </div>
        );

      case 'news':
        return (
          <div className="space-y-4">
            <SettingToggle
              label="التمرير التلقائي"
              description="تمرير الأخبار تلقائياً"
              checked={settings.news.autoScroll}
              onChange={(v) => updateSetting('news', 'autoScroll', v)}
            />
            <SettingToggle
              label="عرض الصور"
              description="إظهار صور الأخبار"
              checked={settings.news.showImages}
              onChange={(v) => updateSetting('news', 'showImages', v)}
            />
          </div>
        );

      case 'ai-assistant':
        return (
          <div className="space-y-4">
            <SettingToggle
              label="تفعيل الفقاعة العائمة"
              description="إظهار المساعد الذكي كزر عائم"
              checked={settings.aiAssistant.bubbleEnabled}
              onChange={(v) => updateSetting('aiAssistant', 'bubbleEnabled', v)}
            />
            <SettingToggle
              label="النطق التلقائي"
              description="قراءة ردود المساعد صوتياً"
              checked={settings.aiAssistant.autoSpeak}
              onChange={(v) => updateSetting('aiAssistant', 'autoSpeak', v)}
            />
            <SettingToggle
              label="الظهور في كل الصفحات"
              description="عرض الفقاعة في جميع صفحات التطبيق"
              checked={settings.aiAssistant.showOnAllPages}
              onChange={(v) => updateSetting('aiAssistant', 'showOnAllPages', v)}
            />
            <SettingToggle
              label="الأوامر الصوتية"
              description="تفعيل التحدث مع المساعد صوتياً"
              checked={settings.aiAssistant.voiceEnabled}
              onChange={(v) => updateSetting('aiAssistant', 'voiceEnabled', v)}
            />
            <SettingToggle
              label="الاقتراحات السريعة"
              description="عرض اقتراحات الأسئلة الشائعة"
              checked={settings.aiAssistant.quickSuggestions}
              onChange={(v) => updateSetting('aiAssistant', 'quickSuggestions', v)}
            />
          </div>
        );

      default:
        return <div className="text-center text-muted-foreground">اختر قسماً لعرض إعداداته</div>;
    }
  };

  if (!isOpen) return null;

  return (
    <AnimatePresence>
      <motion.div
        className="fixed inset-0 z-50 bg-black/50 backdrop-blur-sm"
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        onClick={onClose}
      />
      <motion.div
        dir="rtl"
        className="fixed inset-4 md:inset-10 z-50 bg-background rounded-2xl shadow-2xl overflow-hidden"
        initial={{ scale: 0.9, opacity: 0 }}
        animate={{ scale: 1, opacity: 1 }}
        exit={{ scale: 0.9, opacity: 0 }}
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between p-4 border-b bg-gradient-to-r from-[#01411C] to-[#065f41]">
          <div className="flex items-center gap-3">
            <Settings className="w-6 h-6 text-[#D4AF37]" />
            <div>
              <h2 className="text-lg font-bold text-white">إعدادات التطبيق الشامل</h2>
              <p className="text-sm text-white/70">مركز التحكم الموحد لجميع الميزات</p>
            </div>
          </div>
          <Button variant="ghost" size="icon" onClick={onClose} className="text-white hover:bg-white/20">
            <X className="w-5 h-5" />
          </Button>
        </div>

        {/* Content */}
        <div className="flex h-[calc(100%-80px)]">
          {/* Sidebar - Sections List */}
          <div className="w-72 border-l bg-muted/30">
            <ScrollArea className="h-full">
              <div className="p-3 space-y-1">
                {SETTINGS_SECTIONS.map((section) => {
                  const Icon = section.icon;
                  return (
                    <button
                      key={section.id}
                      onClick={() => setActiveSection(section.id)}
                      className={`w-full flex items-center gap-3 p-3 rounded-lg text-right transition-all ${
                        activeSection === section.id
                          ? 'bg-primary text-primary-foreground'
                          : 'hover:bg-muted'
                      }`}
                    >
                      <div
                        className={`p-2 rounded-lg ${
                          activeSection === section.id ? 'bg-white/20' : 'bg-muted'
                        }`}
                        style={{ color: activeSection === section.id ? 'white' : section.color }}
                      >
                        <Icon className="w-4 h-4" />
                      </div>
                      <div className="flex-1 min-w-0">
                        <p className="font-medium truncate">{section.label}</p>
                        <p className={`text-xs truncate ${
                          activeSection === section.id ? 'text-white/70' : 'text-muted-foreground'
                        }`}>
                          {section.description}
                        </p>
                      </div>
                      <ChevronLeft className="w-4 h-4 opacity-50" />
                    </button>
                  );
                })}
              </div>
            </ScrollArea>
          </div>

          {/* Main Content */}
          <div className="flex-1 flex flex-col">
            <ScrollArea className="flex-1">
              <div className="p-6">
                {activeSection ? (
                  <div className="space-y-6">
                    <div className="flex items-center gap-3 pb-4 border-b">
                      {(() => {
                        const section = SETTINGS_SECTIONS.find(s => s.id === activeSection);
                        if (!section) return null;
                        const Icon = section.icon;
                        return (
                          <>
                            <div
                              className="p-3 rounded-xl"
                              style={{ backgroundColor: `${section.color}15`, color: section.color }}
                            >
                              <Icon className="w-6 h-6" />
                            </div>
                            <div>
                              <h3 className="text-xl font-bold">{section.label}</h3>
                              <p className="text-muted-foreground">{section.description}</p>
                            </div>
                          </>
                        );
                      })()}
                    </div>
                    {renderSectionSettings(activeSection)}
                  </div>
                ) : (
                  <div className="flex flex-col items-center justify-center h-full text-center py-20">
                    <Settings className="w-16 h-16 text-muted-foreground/30 mb-4" />
                    <h3 className="text-lg font-medium text-muted-foreground">اختر قسماً من القائمة</h3>
                    <p className="text-sm text-muted-foreground/70">لعرض وتعديل إعداداته</p>
                  </div>
                )}
              </div>
            </ScrollArea>

            {/* Footer */}
            {activeSection && (
              <div className="p-4 border-t bg-muted/30 flex justify-end gap-3">
                <Button variant="outline" onClick={() => setActiveSection(null)}>
                  إلغاء
                </Button>
                <Button onClick={saveSettings} className="bg-[#01411C] hover:bg-[#065f41]">
                  حفظ الإعدادات
                </Button>
              </div>
            )}
          </div>
        </div>
      </motion.div>
    </AnimatePresence>
  );
}

// مكون مساعد للتبديلات
function SettingToggle({
  label,
  description,
  checked,
  onChange,
}: {
  label: string;
  description: string;
  checked: boolean;
  onChange: (value: boolean) => void;
}) {
  return (
    <div className="flex items-center justify-between p-4 rounded-lg bg-muted/30 hover:bg-muted/50 transition-colors">
      <div className="flex-1">
        <Label className="font-medium cursor-pointer">{label}</Label>
        <p className="text-sm text-muted-foreground">{description}</p>
      </div>
      <Switch checked={checked} onCheckedChange={onChange} />
    </div>
  );
}

export { ComprehensiveAppSettings };
